### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by anandaroop**
https://artsyproduct.atlassian.net/browse/TRUST-215

This takes care of all known security vulnerabilities as reported by both Github and `yarn audit` 

Looks like it was only dev dependencies that were affected, so impact may be small — but good to do in any case.

### CODE REVIEW

**Review by dblandin — COMMENTED** [review]
LGTM :+1:

**Review by dblandin — APPROVED** [review]

**Comment by dblandin** [comment]
@anandaroop Looks I don't currently have `write` access to this repository so can't merge. Would you mind updating the repository permissions when you have a moment?

**Comment by anandaroop** [comment]
Ah whoops had only give 'read' access to the team previously 🙈

**Comment by artsyit** [comment]
:rocket: PR was released in [`v0.3.1`](https://github.com/artsy/passport-local-with-otp/releases/tag/v0.3.1) :rocket:

**Pull request merged**
